### PR TITLE
ASM-7245 adding missing file and minor changes

### PR DESCRIPTION
**Pull request by ksw2599**

### CODE REVIEW

**Comment by ksw2599** [comment]
@gavin-scott, @aimers1975, @ripienaar: Please review and merge.

**Comment by ripienaar** [comment]
@ksw2599 is the intention to allow the bond to be made by hand or something? what scenario will it already exist?

**Comment by ksw2599** [comment]
@ripienaar what do you mean? made by hand?

**Comment by ripienaar** [comment]
Perhaps made by some other means - here you are chekcing if the bond interface already exist in the interfaces fact and then leaving it unchanged if it does - I am wondering in what scenario that would exist already and what if its not in the same configuration as what we would have configured it? there's nothing to detect if the bond is configured in some other way

**Comment by ksw2599** [comment]
oh I get you.. There are some steps in the bonding setup that shouldn't be run more than once. For both RHEL and SLES, running the same config seems to mess things up. Ideally they should be idempotent, but right now we just skip the bonding config after the 1st time.

**Comment by ripienaar** [comment]
@ksw2599 hmm, ok interesting.  This is the kind of things that should be in commit messages :)

**Pull request merged**
