### PR TITLE
ASM-6829 call ifdown to bring down all interfaces after network stop

### PR DESCRIPTION
**Pull request by ksw2599**
for Intel NICs, the static PXE device seems to get stuck with the IP address and does not go to linkdown properly. This change explicitly calls ifdown after the network stop to ensure that all interfaces would be down.

### CODE REVIEW

**Comment by ksw2599** [comment]
Do not merge yet. Additional validation and tests are required at this point.
- Ensure VM pxe removal workflow is not affected
- Ensure that broadcom NICs are not affected

**Comment by ksw2599** [comment]
@gavin-scott & @aimers1975: The validations are complete. Please feel free to merge now.

**Comment by gavin-scott** [comment]
Still failing on test case in my asmdev environment 3 appliance. Do not merge until we resolve this.

**Comment by gavin-scott** [comment]
Closing in favor of #30

**Pull request closed without merging**
